// Package admin provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.2-0.20250102212541-8bbe226927c9 DO NOT EDIT.
package admin

import (
	"context"
	"io"
	"net/http"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	APIKeyAuthScopes = "APIKeyAuth.Scopes"
	AdminAuthScopes  = "AdminAuth.Scopes"
)

// Defines values for ErrorSchemaWeakPasswordReasons.
const (
	Characters ErrorSchemaWeakPasswordReasons = "characters"
	Length     ErrorSchemaWeakPasswordReasons = "length"
	Pwned      ErrorSchemaWeakPasswordReasons = "pwned"
)

// Defines values for PostAdminGenerateLinkJSONBodyType.
const (
	EmailChangeCurrent PostAdminGenerateLinkJSONBodyType = "email_change_current"
	EmailChangeNew     PostAdminGenerateLinkJSONBodyType = "email_change_new"
	Magiclink          PostAdminGenerateLinkJSONBodyType = "magiclink"
	Recovery           PostAdminGenerateLinkJSONBodyType = "recovery"
	Signup             PostAdminGenerateLinkJSONBodyType = "signup"
)

// Defines values for PostAdminSsoProvidersJSONBodyType.
const (
	Saml PostAdminSsoProvidersJSONBodyType = "saml"
)

// ErrorSchema defines model for ErrorSchema.
type ErrorSchema struct {
	// Code The HTTP status code. Usually missing if `error` is present.
	Code *int `json:"code,omitempty"`

	// Error Certain responses will contain this property with the provided values.
	//
	// Usually one of these:
	//   - invalid_request
	//   - unauthorized_client
	//   - access_denied
	//   - server_error
	//   - temporarily_unavailable
	//   - unsupported_otp_type
	Error *string `json:"error,omitempty"`

	// ErrorCode A short code used to describe the class of error encountered.
	ErrorCode *string `json:"error_code,omitempty"`

	// ErrorDescription Certain responses that have an `error` property may have this property which describes the error.
	ErrorDescription *string `json:"error_description,omitempty"`

	// Msg A basic message describing the problem with the request. Usually missing if `error` is present.
	Msg *string `json:"msg,omitempty"`

	// WeakPassword Only returned on the `/signup` endpoint if the password used is too weak. Inspect the `reasons` and `msg` property to identify the causes.
	WeakPassword *struct {
		Reasons *[]ErrorSchemaWeakPasswordReasons `json:"reasons,omitempty"`
	} `json:"weak_password,omitempty"`
}

// ErrorSchemaWeakPasswordReasons defines model for ErrorSchema.WeakPassword.Reasons.
type ErrorSchemaWeakPasswordReasons string

// IdentitySchema defines model for IdentitySchema.
type IdentitySchema struct {
	CreatedAt    *time.Time              `json:"created_at,omitempty"`
	Email        *openapi_types.Email    `json:"email,omitempty"`
	Id           *openapi_types.UUID     `json:"id,omitempty"`
	IdentityData *map[string]interface{} `json:"identity_data,omitempty"`
	IdentityId   *openapi_types.UUID     `json:"identity_id,omitempty"`
	LastSignInAt *time.Time              `json:"last_sign_in_at,omitempty"`
	Provider     *string                 `json:"provider,omitempty"`
	UpdatedAt    *time.Time              `json:"updated_at,omitempty"`
	UserId       *openapi_types.UUID     `json:"user_id,omitempty"`
}

// MFAFactorSchema Represents a MFA factor.
type MFAFactorSchema struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// FactorType Usually one of:
	// - totp
	// - phone
	// - webauthn
	FactorType       *string             `json:"factor_type,omitempty"`
	FriendlyName     *string             `json:"friendly_name,omitempty"`
	Id               *openapi_types.UUID `json:"id,omitempty"`
	LastChallengedAt *time.Time          `json:"last_challenged_at"`
	Phone            *string             `json:"phone"`

	// Status Usually one of:
	// - verified
	// - unverified
	Status             *string    `json:"status,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
	WebAuthnCredential *string    `json:"web_authn_credential,omitempty"`
}

// SAMLAttributeMappingSchema defines model for SAMLAttributeMappingSchema.
type SAMLAttributeMappingSchema struct {
	Keys *map[string]interface{} `json:"keys,omitempty"`
}

// SSOProviderSchema defines model for SSOProviderSchema.
type SSOProviderSchema struct {
	Id   *openapi_types.UUID `json:"id,omitempty"`
	Saml *struct {
		AttributeMapping *SAMLAttributeMappingSchema `json:"attribute_mapping,omitempty"`
		EntityId         *string                     `json:"entity_id,omitempty"`
		MetadataUrl      *string                     `json:"metadata_url,omitempty"`
		MetadataXml      *string                     `json:"metadata_xml,omitempty"`
	} `json:"saml,omitempty"`
	SsoDomains *[]struct {
		Domain *string `json:"domain,omitempty"`
	} `json:"sso_domains,omitempty"`
}

// UserSchema Object describing the user related to the issued access and refresh tokens.
type UserSchema struct {
	AppMetadata *map[string]interface{} `json:"app_metadata,omitempty"`
	// Deprecated:
	Aud                *string    `json:"aud,omitempty"`
	BannedUntil        *time.Time `json:"banned_until,omitempty"`
	ConfirmationSentAt *time.Time `json:"confirmation_sent_at,omitempty"`
	ConfirmedAt        *time.Time `json:"confirmed_at,omitempty"`
	CreatedAt          *time.Time `json:"created_at,omitempty"`
	DeletedAt          *time.Time `json:"deleted_at,omitempty"`

	// Email User's primary contact email. In most cases you can uniquely identify a user by their email address, but not in all cases.
	Email             *string              `json:"email,omitempty"`
	EmailChangeSentAt *time.Time           `json:"email_change_sent_at,omitempty"`
	EmailConfirmedAt  *time.Time           `json:"email_confirmed_at,omitempty"`
	Factors           *[]MFAFactorSchema   `json:"factors,omitempty"`
	Id                *openapi_types.UUID  `json:"id,omitempty"`
	Identities        *[]IdentitySchema    `json:"identities,omitempty"`
	IsAnonymous       *bool                `json:"is_anonymous,omitempty"`
	LastSignInAt      *time.Time           `json:"last_sign_in_at,omitempty"`
	NewEmail          *openapi_types.Email `json:"new_email,omitempty"`
	NewPhone          *string              `json:"new_phone,omitempty"`

	// Phone User's primary contact phone number. In most cases you can uniquely identify a user by their phone number, but not in all cases.
	Phone                  *string                 `json:"phone,omitempty"`
	PhoneChangeSentAt      *time.Time              `json:"phone_change_sent_at,omitempty"`
	PhoneConfirmedAt       *time.Time              `json:"phone_confirmed_at,omitempty"`
	ReauthenticationSentAt *time.Time              `json:"reauthentication_sent_at,omitempty"`
	RecoverySentAt         *time.Time              `json:"recovery_sent_at,omitempty"`
	Role                   *string                 `json:"role,omitempty"`
	UpdatedAt              *time.Time              `json:"updated_at,omitempty"`
	UserMetadata           *map[string]interface{} `json:"user_metadata,omitempty"`
}

// BadRequestResponse defines model for BadRequestResponse.
type BadRequestResponse = ErrorSchema

// ForbiddenResponse defines model for ForbiddenResponse.
type ForbiddenResponse = ErrorSchema

// UnauthorizedResponse defines model for UnauthorizedResponse.
type UnauthorizedResponse = ErrorSchema

// GetAdminAuditParams defines parameters for GetAdminAudit.
type GetAdminAuditParams struct {
	Page    *int `form:"page,omitempty" json:"page,omitempty"`
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// PostAdminGenerateLinkJSONBody defines parameters for PostAdminGenerateLink.
type PostAdminGenerateLinkJSONBody struct {
	Data       *map[string]interface{}           `json:"data,omitempty"`
	Email      openapi_types.Email               `json:"email"`
	NewEmail   *openapi_types.Email              `json:"new_email,omitempty"`
	Password   *string                           `json:"password,omitempty"`
	RedirectTo *string                           `json:"redirect_to,omitempty"`
	Type       PostAdminGenerateLinkJSONBodyType `json:"type"`
}

// PostAdminGenerateLinkJSONBodyType defines parameters for PostAdminGenerateLink.
type PostAdminGenerateLinkJSONBodyType string

// PostAdminSsoProvidersJSONBody defines parameters for PostAdminSsoProviders.
type PostAdminSsoProvidersJSONBody struct {
	AttributeMapping *SAMLAttributeMappingSchema       `json:"attribute_mapping,omitempty"`
	Domains          *[]string                         `json:"domains,omitempty"`
	MetadataUrl      *string                           `json:"metadata_url,omitempty"`
	MetadataXml      *string                           `json:"metadata_xml,omitempty"`
	Type             PostAdminSsoProvidersJSONBodyType `json:"type"`
}

// PostAdminSsoProvidersJSONBodyType defines parameters for PostAdminSsoProviders.
type PostAdminSsoProvidersJSONBodyType string

// PutAdminSsoProvidersSsoProviderIdJSONBody defines parameters for PutAdminSsoProvidersSsoProviderId.
type PutAdminSsoProvidersSsoProviderIdJSONBody struct {
	AttributeMapping *SAMLAttributeMappingSchema `json:"attribute_mapping,omitempty"`
	Domains          *[]string                   `json:"domains,omitempty"`
	MetadataUrl      *string                     `json:"metadata_url,omitempty"`
	MetadataXml      *string                     `json:"metadata_xml,omitempty"`
}

// GetAdminUsersParams defines parameters for GetAdminUsers.
type GetAdminUsersParams struct {
	Page    *int `form:"page,omitempty" json:"page,omitempty"`
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// PutAdminUsersUserIdFactorsFactorIdJSONBody defines parameters for PutAdminUsersUserIdFactorsFactorId.
type PutAdminUsersUserIdFactorsFactorIdJSONBody = map[string]interface{}

// PostInviteJSONBody defines parameters for PostInvite.
type PostInviteJSONBody struct {
	Data  *map[string]interface{} `json:"data,omitempty"`
	Email string                  `json:"email"`
}

// PostAdminGenerateLinkJSONRequestBody defines body for PostAdminGenerateLink for application/json ContentType.
type PostAdminGenerateLinkJSONRequestBody PostAdminGenerateLinkJSONBody

// PostAdminSsoProvidersJSONRequestBody defines body for PostAdminSsoProviders for application/json ContentType.
type PostAdminSsoProvidersJSONRequestBody PostAdminSsoProvidersJSONBody

// PutAdminSsoProvidersSsoProviderIdJSONRequestBody defines body for PutAdminSsoProvidersSsoProviderId for application/json ContentType.
type PutAdminSsoProvidersSsoProviderIdJSONRequestBody PutAdminSsoProvidersSsoProviderIdJSONBody

// PutAdminUsersUserIdJSONRequestBody defines body for PutAdminUsersUserId for application/json ContentType.
type PutAdminUsersUserIdJSONRequestBody = UserSchema

// PutAdminUsersUserIdFactorsFactorIdJSONRequestBody defines body for PutAdminUsersUserIdFactorsFactorId for application/json ContentType.
type PutAdminUsersUserIdFactorsFactorIdJSONRequestBody = PutAdminUsersUserIdFactorsFactorIdJSONBody

// PostInviteJSONRequestBody defines body for PostInvite for application/json ContentType.
type PostInviteJSONRequestBody PostInviteJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	_ = "STUB: not implemented"
	// create a client with sane default values
	return nil, nil
}

// mutate client and add all optional params

// ensure the server URL always has a trailing slash

// create httpClient, if not already present

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	_ = "STUB: not implemented"
	return *new(ClientOption)
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	_ = "STUB: not implemented"
	return *new(ClientOption)
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAdminAudit request
	GetAdminAudit(ctx context.Context, params *GetAdminAuditParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAdminGenerateLinkWithBody request with any body
	PostAdminGenerateLinkWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAdminGenerateLink(ctx context.Context, body PostAdminGenerateLinkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminSsoProviders request
	GetAdminSsoProviders(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAdminSsoProvidersWithBody request with any body
	PostAdminSsoProvidersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAdminSsoProviders(ctx context.Context, body PostAdminSsoProvidersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAdminSsoProvidersSsoProviderId request
	DeleteAdminSsoProvidersSsoProviderId(ctx context.Context, ssoProviderId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminSsoProvidersSsoProviderId request
	GetAdminSsoProvidersSsoProviderId(ctx context.Context, ssoProviderId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutAdminSsoProvidersSsoProviderIdWithBody request with any body
	PutAdminSsoProvidersSsoProviderIdWithBody(ctx context.Context, ssoProviderId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutAdminSsoProvidersSsoProviderId(ctx context.Context, ssoProviderId openapi_types.UUID, body PutAdminSsoProvidersSsoProviderIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminUsers request
	GetAdminUsers(ctx context.Context, params *GetAdminUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAdminUsersUserId request
	DeleteAdminUsersUserId(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminUsersUserId request
	GetAdminUsersUserId(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutAdminUsersUserIdWithBody request with any body
	PutAdminUsersUserIdWithBody(ctx context.Context, userId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutAdminUsersUserId(ctx context.Context, userId openapi_types.UUID, body PutAdminUsersUserIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminUsersUserIdFactors request
	GetAdminUsersUserIdFactors(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAdminUsersUserIdFactorsFactorId request
	DeleteAdminUsersUserIdFactorsFactorId(ctx context.Context, userId openapi_types.UUID, factorId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutAdminUsersUserIdFactorsFactorIdWithBody request with any body
	PutAdminUsersUserIdFactorsFactorIdWithBody(ctx context.Context, userId openapi_types.UUID, factorId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutAdminUsersUserIdFactorsFactorId(ctx context.Context, userId openapi_types.UUID, factorId openapi_types.UUID, body PutAdminUsersUserIdFactorsFactorIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostInviteWithBody request with any body
	PostInviteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostInvite(ctx context.Context, body PostInviteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAdminAudit(ctx context.Context, params *GetAdminAuditParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) PostAdminGenerateLinkWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) PostAdminGenerateLink(ctx context.Context, body PostAdminGenerateLinkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) GetAdminSsoProviders(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) PostAdminSsoProvidersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) PostAdminSsoProviders(ctx context.Context, body PostAdminSsoProvidersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) DeleteAdminSsoProvidersSsoProviderId(ctx context.Context, ssoProviderId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) GetAdminSsoProvidersSsoProviderId(ctx context.Context, ssoProviderId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) PutAdminSsoProvidersSsoProviderIdWithBody(ctx context.Context, ssoProviderId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) PutAdminSsoProvidersSsoProviderId(ctx context.Context, ssoProviderId openapi_types.UUID, body PutAdminSsoProvidersSsoProviderIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) GetAdminUsers(ctx context.Context, params *GetAdminUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) DeleteAdminUsersUserId(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) GetAdminUsersUserId(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) PutAdminUsersUserIdWithBody(ctx context.Context, userId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) PutAdminUsersUserId(ctx context.Context, userId openapi_types.UUID, body PutAdminUsersUserIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) GetAdminUsersUserIdFactors(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) DeleteAdminUsersUserIdFactorsFactorId(ctx context.Context, userId openapi_types.UUID, factorId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) PutAdminUsersUserIdFactorsFactorIdWithBody(ctx context.Context, userId openapi_types.UUID, factorId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) PutAdminUsersUserIdFactorsFactorId(ctx context.Context, userId openapi_types.UUID, factorId openapi_types.UUID, body PutAdminUsersUserIdFactorsFactorIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) PostInviteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) PostInvite(ctx context.Context, body PostInviteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGetAdminAuditRequest generates requests for GetAdminAudit
func NewGetAdminAuditRequest(server string, params *GetAdminAuditParams) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPostAdminGenerateLinkRequest calls the generic PostAdminGenerateLink builder with application/json body
func NewPostAdminGenerateLinkRequest(server string, body PostAdminGenerateLinkJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPostAdminGenerateLinkRequestWithBody generates requests for PostAdminGenerateLink with any type of body
func NewPostAdminGenerateLinkRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGetAdminSsoProvidersRequest generates requests for GetAdminSsoProviders
func NewGetAdminSsoProvidersRequest(server string) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPostAdminSsoProvidersRequest calls the generic PostAdminSsoProviders builder with application/json body
func NewPostAdminSsoProvidersRequest(server string, body PostAdminSsoProvidersJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPostAdminSsoProvidersRequestWithBody generates requests for PostAdminSsoProviders with any type of body
func NewPostAdminSsoProvidersRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewDeleteAdminSsoProvidersSsoProviderIdRequest generates requests for DeleteAdminSsoProvidersSsoProviderId
func NewDeleteAdminSsoProvidersSsoProviderIdRequest(server string, ssoProviderId openapi_types.UUID) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGetAdminSsoProvidersSsoProviderIdRequest generates requests for GetAdminSsoProvidersSsoProviderId
func NewGetAdminSsoProvidersSsoProviderIdRequest(server string, ssoProviderId openapi_types.UUID) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPutAdminSsoProvidersSsoProviderIdRequest calls the generic PutAdminSsoProvidersSsoProviderId builder with application/json body
func NewPutAdminSsoProvidersSsoProviderIdRequest(server string, ssoProviderId openapi_types.UUID, body PutAdminSsoProvidersSsoProviderIdJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPutAdminSsoProvidersSsoProviderIdRequestWithBody generates requests for PutAdminSsoProvidersSsoProviderId with any type of body
func NewPutAdminSsoProvidersSsoProviderIdRequestWithBody(server string, ssoProviderId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGetAdminUsersRequest generates requests for GetAdminUsers
func NewGetAdminUsersRequest(server string, params *GetAdminUsersParams) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewDeleteAdminUsersUserIdRequest generates requests for DeleteAdminUsersUserId
func NewDeleteAdminUsersUserIdRequest(server string, userId openapi_types.UUID) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGetAdminUsersUserIdRequest generates requests for GetAdminUsersUserId
func NewGetAdminUsersUserIdRequest(server string, userId openapi_types.UUID) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPutAdminUsersUserIdRequest calls the generic PutAdminUsersUserId builder with application/json body
func NewPutAdminUsersUserIdRequest(server string, userId openapi_types.UUID, body PutAdminUsersUserIdJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPutAdminUsersUserIdRequestWithBody generates requests for PutAdminUsersUserId with any type of body
func NewPutAdminUsersUserIdRequestWithBody(server string, userId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGetAdminUsersUserIdFactorsRequest generates requests for GetAdminUsersUserIdFactors
func NewGetAdminUsersUserIdFactorsRequest(server string, userId openapi_types.UUID) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewDeleteAdminUsersUserIdFactorsFactorIdRequest generates requests for DeleteAdminUsersUserIdFactorsFactorId
func NewDeleteAdminUsersUserIdFactorsFactorIdRequest(server string, userId openapi_types.UUID, factorId openapi_types.UUID) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPutAdminUsersUserIdFactorsFactorIdRequest calls the generic PutAdminUsersUserIdFactorsFactorId builder with application/json body
func NewPutAdminUsersUserIdFactorsFactorIdRequest(server string, userId openapi_types.UUID, factorId openapi_types.UUID, body PutAdminUsersUserIdFactorsFactorIdJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPutAdminUsersUserIdFactorsFactorIdRequestWithBody generates requests for PutAdminUsersUserIdFactorsFactorId with any type of body
func NewPutAdminUsersUserIdFactorsFactorIdRequestWithBody(server string, userId openapi_types.UUID, factorId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPostInviteRequest calls the generic PostInvite builder with application/json body
func NewPostInviteRequest(server string, body PostInviteJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPostInviteRequestWithBody generates requests for PostInvite with any type of body
func NewPostInviteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	_ = "STUB: not implemented"
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption { _ = "STUB: not implemented"; return *new(ClientOption) }

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAdminAuditWithResponse request
	GetAdminAuditWithResponse(ctx context.Context, params *GetAdminAuditParams, reqEditors ...RequestEditorFn) (*GetAdminAuditResponse, error)

	// PostAdminGenerateLinkWithBodyWithResponse request with any body
	PostAdminGenerateLinkWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminGenerateLinkResponse, error)

	PostAdminGenerateLinkWithResponse(ctx context.Context, body PostAdminGenerateLinkJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminGenerateLinkResponse, error)

	// GetAdminSsoProvidersWithResponse request
	GetAdminSsoProvidersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminSsoProvidersResponse, error)

	// PostAdminSsoProvidersWithBodyWithResponse request with any body
	PostAdminSsoProvidersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminSsoProvidersResponse, error)

	PostAdminSsoProvidersWithResponse(ctx context.Context, body PostAdminSsoProvidersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminSsoProvidersResponse, error)

	// DeleteAdminSsoProvidersSsoProviderIdWithResponse request
	DeleteAdminSsoProvidersSsoProviderIdWithResponse(ctx context.Context, ssoProviderId openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteAdminSsoProvidersSsoProviderIdResponse, error)

	// GetAdminSsoProvidersSsoProviderIdWithResponse request
	GetAdminSsoProvidersSsoProviderIdWithResponse(ctx context.Context, ssoProviderId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetAdminSsoProvidersSsoProviderIdResponse, error)

	// PutAdminSsoProvidersSsoProviderIdWithBodyWithResponse request with any body
	PutAdminSsoProvidersSsoProviderIdWithBodyWithResponse(ctx context.Context, ssoProviderId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutAdminSsoProvidersSsoProviderIdResponse, error)

	PutAdminSsoProvidersSsoProviderIdWithResponse(ctx context.Context, ssoProviderId openapi_types.UUID, body PutAdminSsoProvidersSsoProviderIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutAdminSsoProvidersSsoProviderIdResponse, error)

	// GetAdminUsersWithResponse request
	GetAdminUsersWithResponse(ctx context.Context, params *GetAdminUsersParams, reqEditors ...RequestEditorFn) (*GetAdminUsersResponse, error)

	// DeleteAdminUsersUserIdWithResponse request
	DeleteAdminUsersUserIdWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteAdminUsersUserIdResponse, error)

	// GetAdminUsersUserIdWithResponse request
	GetAdminUsersUserIdWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetAdminUsersUserIdResponse, error)

	// PutAdminUsersUserIdWithBodyWithResponse request with any body
	PutAdminUsersUserIdWithBodyWithResponse(ctx context.Context, userId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutAdminUsersUserIdResponse, error)

	PutAdminUsersUserIdWithResponse(ctx context.Context, userId openapi_types.UUID, body PutAdminUsersUserIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutAdminUsersUserIdResponse, error)

	// GetAdminUsersUserIdFactorsWithResponse request
	GetAdminUsersUserIdFactorsWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetAdminUsersUserIdFactorsResponse, error)

	// DeleteAdminUsersUserIdFactorsFactorIdWithResponse request
	DeleteAdminUsersUserIdFactorsFactorIdWithResponse(ctx context.Context, userId openapi_types.UUID, factorId openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteAdminUsersUserIdFactorsFactorIdResponse, error)

	// PutAdminUsersUserIdFactorsFactorIdWithBodyWithResponse request with any body
	PutAdminUsersUserIdFactorsFactorIdWithBodyWithResponse(ctx context.Context, userId openapi_types.UUID, factorId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutAdminUsersUserIdFactorsFactorIdResponse, error)

	PutAdminUsersUserIdFactorsFactorIdWithResponse(ctx context.Context, userId openapi_types.UUID, factorId openapi_types.UUID, body PutAdminUsersUserIdFactorsFactorIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutAdminUsersUserIdFactorsFactorIdResponse, error)

	// PostInviteWithBodyWithResponse request with any body
	PostInviteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostInviteResponse, error)

	PostInviteWithResponse(ctx context.Context, body PostInviteJSONRequestBody, reqEditors ...RequestEditorFn) (*PostInviteResponse, error)
}

type GetAdminAuditResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]struct {
		CreatedAt *time.Time          `json:"created_at,omitempty"`
		Id        *openapi_types.UUID `json:"id,omitempty"`
		IpAddress *string             `json:"ip_address,omitempty"`
		Payload   *struct {
			// Action Usually one of these values:
			// - login
			// - logout
			// - invite_accepted
			// - user_signedup
			// - user_invited
			// - user_deleted
			// - user_modified
			// - user_recovery_requested
			// - user_reauthenticate_requested
			// - user_confirmation_requested
			// - user_repeated_signup
			// - user_updated_password
			// - token_revoked
			// - token_refreshed
			// - generate_recovery_codes
			// - factor_in_progress
			// - factor_unenrolled
			// - challenge_created
			// - verification_attempted
			// - factor_deleted
			// - recovery_codes_deleted
			// - factor_updated
			// - mfa_code_login
			Action        *string `json:"action,omitempty"`
			ActorId       *string `json:"actor_id,omitempty"`
			ActorName     *string `json:"actor_name,omitempty"`
			ActorUsername *string `json:"actor_username,omitempty"`

			// ActorViaSso Whether the actor used a SSO protocol (like SAML 2.0 or OIDC) to authenticate.
			ActorViaSso *bool `json:"actor_via_sso,omitempty"`

			// LogType Usually one of these values:
			// - account
			// - team
			// - token
			// - user
			// - factor
			// - recovery_codes
			LogType *string                 `json:"log_type,omitempty"`
			Traits  *map[string]interface{} `json:"traits,omitempty"`
		} `json:"payload,omitempty"`
	}
	JSON401 *UnauthorizedResponse
	JSON403 *ForbiddenResponse
}

// Status returns HTTPResponse.Status
func (r GetAdminAuditResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminAuditResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type PostAdminGenerateLinkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		ActionLink           *string                `json:"action_link,omitempty"`
		EmailOtp             *string                `json:"email_otp,omitempty"`
		HashedToken          *string                `json:"hashed_token,omitempty"`
		RedirectTo           *string                `json:"redirect_to,omitempty"`
		VerificationType     *string                `json:"verification_type,omitempty"`
		AdditionalProperties map[string]interface{} `json:"-"`
	}
	JSON400 *BadRequestResponse
	JSON401 *UnauthorizedResponse
	JSON403 *ForbiddenResponse
	JSON404 *ErrorSchema
	JSON422 *ErrorSchema
}

// Status returns HTTPResponse.Status
func (r PostAdminGenerateLinkResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r PostAdminGenerateLinkResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type GetAdminSsoProvidersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Items *[]SSOProviderSchema `json:"items,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetAdminSsoProvidersResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminSsoProvidersResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type PostAdminSsoProvidersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SSOProviderSchema
	JSON400      *BadRequestResponse
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
}

// Status returns HTTPResponse.Status
func (r PostAdminSsoProvidersResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r PostAdminSsoProvidersResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type DeleteAdminSsoProvidersSsoProviderIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SSOProviderSchema
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *ErrorSchema
}

// Status returns HTTPResponse.Status
func (r DeleteAdminSsoProvidersSsoProviderIdResponse) Status() string {
	_ = "STUB: not implemented"
	return ""
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAdminSsoProvidersSsoProviderIdResponse) StatusCode() int {
	_ = "STUB: not implemented"
	return 0
}

type GetAdminSsoProvidersSsoProviderIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SSOProviderSchema
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *ErrorSchema
}

// Status returns HTTPResponse.Status
func (r GetAdminSsoProvidersSsoProviderIdResponse) Status() string {
	_ = "STUB: not implemented"
	return ""
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminSsoProvidersSsoProviderIdResponse) StatusCode() int {
	_ = "STUB: not implemented"
	return 0
}

type PutAdminSsoProvidersSsoProviderIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SSOProviderSchema
	JSON400      *BadRequestResponse
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *ErrorSchema
}

// Status returns HTTPResponse.Status
func (r PutAdminSsoProvidersSsoProviderIdResponse) Status() string {
	_ = "STUB: not implemented"
	return ""
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutAdminSsoProvidersSsoProviderIdResponse) StatusCode() int {
	_ = "STUB: not implemented"
	return 0
}

type GetAdminUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Deprecated:
		Aud   *string       `json:"aud,omitempty"`
		Users *[]UserSchema `json:"users,omitempty"`
	}
	JSON401 *UnauthorizedResponse
	JSON403 *ForbiddenResponse
}

// Status returns HTTPResponse.Status
func (r GetAdminUsersResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminUsersResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type DeleteAdminUsersUserIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserSchema
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *ErrorSchema
}

// Status returns HTTPResponse.Status
func (r DeleteAdminUsersUserIdResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAdminUsersUserIdResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type GetAdminUsersUserIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserSchema
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *ErrorSchema
}

// Status returns HTTPResponse.Status
func (r GetAdminUsersUserIdResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminUsersUserIdResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type PutAdminUsersUserIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserSchema
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *ErrorSchema
}

// Status returns HTTPResponse.Status
func (r PutAdminUsersUserIdResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r PutAdminUsersUserIdResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type GetAdminUsersUserIdFactorsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]MFAFactorSchema
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *ErrorSchema
}

// Status returns HTTPResponse.Status
func (r GetAdminUsersUserIdFactorsResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminUsersUserIdFactorsResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type DeleteAdminUsersUserIdFactorsFactorIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MFAFactorSchema
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *ErrorSchema
}

// Status returns HTTPResponse.Status
func (r DeleteAdminUsersUserIdFactorsFactorIdResponse) Status() string {
	_ = "STUB: not implemented"
	return ""
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAdminUsersUserIdFactorsFactorIdResponse) StatusCode() int {
	_ = "STUB: not implemented"
	return 0
}

type PutAdminUsersUserIdFactorsFactorIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MFAFactorSchema
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *ErrorSchema
}

// Status returns HTTPResponse.Status
func (r PutAdminUsersUserIdFactorsFactorIdResponse) Status() string {
	_ = "STUB: not implemented"
	return ""
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutAdminUsersUserIdFactorsFactorIdResponse) StatusCode() int {
	_ = "STUB: not implemented"
	return 0
}

type PostInviteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserSchema
	JSON400      *BadRequestResponse
	JSON422      *ErrorSchema
}

// Status returns HTTPResponse.Status
func (r PostInviteResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r PostInviteResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

// GetAdminAuditWithResponse request returning *GetAdminAuditResponse
func (c *ClientWithResponses) GetAdminAuditWithResponse(ctx context.Context, params *GetAdminAuditParams, reqEditors ...RequestEditorFn) (*GetAdminAuditResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PostAdminGenerateLinkWithBodyWithResponse request with arbitrary body returning *PostAdminGenerateLinkResponse
func (c *ClientWithResponses) PostAdminGenerateLinkWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminGenerateLinkResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) PostAdminGenerateLinkWithResponse(ctx context.Context, body PostAdminGenerateLinkJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminGenerateLinkResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAdminSsoProvidersWithResponse request returning *GetAdminSsoProvidersResponse
func (c *ClientWithResponses) GetAdminSsoProvidersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminSsoProvidersResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PostAdminSsoProvidersWithBodyWithResponse request with arbitrary body returning *PostAdminSsoProvidersResponse
func (c *ClientWithResponses) PostAdminSsoProvidersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminSsoProvidersResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) PostAdminSsoProvidersWithResponse(ctx context.Context, body PostAdminSsoProvidersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminSsoProvidersResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAdminSsoProvidersSsoProviderIdWithResponse request returning *DeleteAdminSsoProvidersSsoProviderIdResponse
func (c *ClientWithResponses) DeleteAdminSsoProvidersSsoProviderIdWithResponse(ctx context.Context, ssoProviderId openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteAdminSsoProvidersSsoProviderIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAdminSsoProvidersSsoProviderIdWithResponse request returning *GetAdminSsoProvidersSsoProviderIdResponse
func (c *ClientWithResponses) GetAdminSsoProvidersSsoProviderIdWithResponse(ctx context.Context, ssoProviderId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetAdminSsoProvidersSsoProviderIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutAdminSsoProvidersSsoProviderIdWithBodyWithResponse request with arbitrary body returning *PutAdminSsoProvidersSsoProviderIdResponse
func (c *ClientWithResponses) PutAdminSsoProvidersSsoProviderIdWithBodyWithResponse(ctx context.Context, ssoProviderId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutAdminSsoProvidersSsoProviderIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) PutAdminSsoProvidersSsoProviderIdWithResponse(ctx context.Context, ssoProviderId openapi_types.UUID, body PutAdminSsoProvidersSsoProviderIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutAdminSsoProvidersSsoProviderIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAdminUsersWithResponse request returning *GetAdminUsersResponse
func (c *ClientWithResponses) GetAdminUsersWithResponse(ctx context.Context, params *GetAdminUsersParams, reqEditors ...RequestEditorFn) (*GetAdminUsersResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAdminUsersUserIdWithResponse request returning *DeleteAdminUsersUserIdResponse
func (c *ClientWithResponses) DeleteAdminUsersUserIdWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteAdminUsersUserIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAdminUsersUserIdWithResponse request returning *GetAdminUsersUserIdResponse
func (c *ClientWithResponses) GetAdminUsersUserIdWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetAdminUsersUserIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutAdminUsersUserIdWithBodyWithResponse request with arbitrary body returning *PutAdminUsersUserIdResponse
func (c *ClientWithResponses) PutAdminUsersUserIdWithBodyWithResponse(ctx context.Context, userId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutAdminUsersUserIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) PutAdminUsersUserIdWithResponse(ctx context.Context, userId openapi_types.UUID, body PutAdminUsersUserIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutAdminUsersUserIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAdminUsersUserIdFactorsWithResponse request returning *GetAdminUsersUserIdFactorsResponse
func (c *ClientWithResponses) GetAdminUsersUserIdFactorsWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetAdminUsersUserIdFactorsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteAdminUsersUserIdFactorsFactorIdWithResponse request returning *DeleteAdminUsersUserIdFactorsFactorIdResponse
func (c *ClientWithResponses) DeleteAdminUsersUserIdFactorsFactorIdWithResponse(ctx context.Context, userId openapi_types.UUID, factorId openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteAdminUsersUserIdFactorsFactorIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PutAdminUsersUserIdFactorsFactorIdWithBodyWithResponse request with arbitrary body returning *PutAdminUsersUserIdFactorsFactorIdResponse
func (c *ClientWithResponses) PutAdminUsersUserIdFactorsFactorIdWithBodyWithResponse(ctx context.Context, userId openapi_types.UUID, factorId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutAdminUsersUserIdFactorsFactorIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) PutAdminUsersUserIdFactorsFactorIdWithResponse(ctx context.Context, userId openapi_types.UUID, factorId openapi_types.UUID, body PutAdminUsersUserIdFactorsFactorIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutAdminUsersUserIdFactorsFactorIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PostInviteWithBodyWithResponse request with arbitrary body returning *PostInviteResponse
func (c *ClientWithResponses) PostInviteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostInviteResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) PostInviteWithResponse(ctx context.Context, body PostInviteJSONRequestBody, reqEditors ...RequestEditorFn) (*PostInviteResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGetAdminAuditResponse parses an HTTP response from a GetAdminAuditWithResponse call
func ParseGetAdminAuditResponse(rsp *http.Response) (*GetAdminAuditResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Action Usually one of these values:
// - login
// - logout
// - invite_accepted
// - user_signedup
// - user_invited
// - user_deleted
// - user_modified
// - user_recovery_requested
// - user_reauthenticate_requested
// - user_confirmation_requested
// - user_repeated_signup
// - user_updated_password
// - token_revoked
// - token_refreshed
// - generate_recovery_codes
// - factor_in_progress
// - factor_unenrolled
// - challenge_created
// - verification_attempted
// - factor_deleted
// - recovery_codes_deleted
// - factor_updated
// - mfa_code_login

// ActorViaSso Whether the actor used a SSO protocol (like SAML 2.0 or OIDC) to authenticate.

// LogType Usually one of these values:
// - account
// - team
// - token
// - user
// - factor
// - recovery_codes

// ParsePostAdminGenerateLinkResponse parses an HTTP response from a PostAdminGenerateLinkWithResponse call
func ParsePostAdminGenerateLinkResponse(rsp *http.Response) (*PostAdminGenerateLinkResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGetAdminSsoProvidersResponse parses an HTTP response from a GetAdminSsoProvidersWithResponse call
func ParseGetAdminSsoProvidersResponse(rsp *http.Response) (*GetAdminSsoProvidersResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParsePostAdminSsoProvidersResponse parses an HTTP response from a PostAdminSsoProvidersWithResponse call
func ParsePostAdminSsoProvidersResponse(rsp *http.Response) (*PostAdminSsoProvidersResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseDeleteAdminSsoProvidersSsoProviderIdResponse parses an HTTP response from a DeleteAdminSsoProvidersSsoProviderIdWithResponse call
func ParseDeleteAdminSsoProvidersSsoProviderIdResponse(rsp *http.Response) (*DeleteAdminSsoProvidersSsoProviderIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGetAdminSsoProvidersSsoProviderIdResponse parses an HTTP response from a GetAdminSsoProvidersSsoProviderIdWithResponse call
func ParseGetAdminSsoProvidersSsoProviderIdResponse(rsp *http.Response) (*GetAdminSsoProvidersSsoProviderIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParsePutAdminSsoProvidersSsoProviderIdResponse parses an HTTP response from a PutAdminSsoProvidersSsoProviderIdWithResponse call
func ParsePutAdminSsoProvidersSsoProviderIdResponse(rsp *http.Response) (*PutAdminSsoProvidersSsoProviderIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGetAdminUsersResponse parses an HTTP response from a GetAdminUsersWithResponse call
func ParseGetAdminUsersResponse(rsp *http.Response) (*GetAdminUsersResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Deprecated:

// ParseDeleteAdminUsersUserIdResponse parses an HTTP response from a DeleteAdminUsersUserIdWithResponse call
func ParseDeleteAdminUsersUserIdResponse(rsp *http.Response) (*DeleteAdminUsersUserIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGetAdminUsersUserIdResponse parses an HTTP response from a GetAdminUsersUserIdWithResponse call
func ParseGetAdminUsersUserIdResponse(rsp *http.Response) (*GetAdminUsersUserIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParsePutAdminUsersUserIdResponse parses an HTTP response from a PutAdminUsersUserIdWithResponse call
func ParsePutAdminUsersUserIdResponse(rsp *http.Response) (*PutAdminUsersUserIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGetAdminUsersUserIdFactorsResponse parses an HTTP response from a GetAdminUsersUserIdFactorsWithResponse call
func ParseGetAdminUsersUserIdFactorsResponse(rsp *http.Response) (*GetAdminUsersUserIdFactorsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseDeleteAdminUsersUserIdFactorsFactorIdResponse parses an HTTP response from a DeleteAdminUsersUserIdFactorsFactorIdWithResponse call
func ParseDeleteAdminUsersUserIdFactorsFactorIdResponse(rsp *http.Response) (*DeleteAdminUsersUserIdFactorsFactorIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParsePutAdminUsersUserIdFactorsFactorIdResponse parses an HTTP response from a PutAdminUsersUserIdFactorsFactorIdWithResponse call
func ParsePutAdminUsersUserIdFactorsFactorIdResponse(rsp *http.Response) (*PutAdminUsersUserIdFactorsFactorIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParsePostInviteResponse parses an HTTP response from a PostInviteWithResponse call
func ParsePostInviteResponse(rsp *http.Response) (*PostInviteResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
